# “Part of this GitHub Actions workflow was optimized with the assistance of ChatGPT by OpenAI.”
name: Run tests

on: 
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Cache Conda Environment
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
          restore-keys: conda-${{ runner.os }}-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: AEsensor_arx
          environment-file: environment.yml
          python-version: 3.11
          auto-update-conda: true
          auto-activate-base: false

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run MATLAB tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          select-by-folder: test/matlab
          test-results-junit: test-results/results.xml

      - name: Run Python Tests
        run: |
          conda install --yes pytest pytest-cov
          pytest ./test/python/test_remove_resp_digitalfilt.py --cov=./src --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}